In [1]:
import pandas as pd

In [4]:
help(pd.DataFrame)

Help on class DataFrame in module pandas.core.frame:

class DataFrame(pandas.core.generic.NDFrame, pandas.core.arraylike.OpsMixin)
 |  DataFrame(data=None, index: 'Optional[Axes]' = None, columns: 'Optional[Axes]' = None, dtype: 'Optional[Dtype]' = None, copy: 'bool' = False)
 |
 |  Two-dimensional, size-mutable, potentially heterogeneous tabular data.
 |
 |  Data structure also contains labeled axes (rows and columns).
 |  Arithmetic operations align on both row and column labels. Can be
 |  thought of as a dict-like container for Series objects. The primary
 |  pandas data structure.
 |
 |  Parameters
 |  ----------
 |  data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
 |      Dict can contain Series, arrays, constants, dataclass or list-like objects. If
 |      data is a dict, column order follows insertion-order.
 |
 |      .. versionchanged:: 0.25.0
 |         If data is a list of dicts, column order follows insertion-order.
 |
 |  index : Index or array-like
 |      Index to use for resulting frame. Will default to RangeIndex if
 |      no indexing information part of input data and no index provided.
 |  columns : Index or array-like
 |      Column labels to use for resulting frame. Will default to
 |      RangeIndex (0, 1, 2, ..., n) if no column labels are provided.
 |  dtype : dtype, default None
 |      Data type to force. Only a single dtype is allowed. If None, infer.
 |  copy : bool, default False
 |      Copy data from inputs. Only affects DataFrame / 2d ndarray input.
 |
 |  See Also
 |  --------
 |  DataFrame.from_records : Constructor from tuples, also record arrays.
 |  DataFrame.from_dict : From dicts of Series, arrays, or dicts.
 |  read_csv : Read a comma-separated values (csv) file into DataFrame.
 |  read_table : Read general delimited file into DataFrame.
 |  read_clipboard : Read text from clipboard into DataFrame.
 |
 |  Examples
 |  --------
 |  Constructing DataFrame from a dictionary.
 |
 |  >>> d = {'col1': [1, 2], 'col2': [3, 4]}
 |  >>> df = pd.DataFrame(data=d)
 |  >>> df
 |     col1  col2
 |  0     1     3
 |  1     2     4
 |
 |  Notice that the inferred dtype is int64.
 |
 |  >>> df.dtypes
 |  col1    int64
 |  col2    int64
 |  dtype: object
 |
 |  To enforce a single dtype:
 |
 |  >>> df = pd.DataFrame(data=d, dtype=np.int8)
 |  >>> df.dtypes
 |  col1    int8
 |  col2    int8
 |  dtype: object
 |
 |  Constructing DataFrame from numpy ndarray:
 |
 |  >>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
 |  ...                    columns=['a', 'b', 'c'])
 |  >>> df2
 |     a  b  c
 |  0  1  2  3
 |  1  4  5  6
 |  2  7  8  9
 |
 |  Constructing DataFrame from dataclass:
 |
 |  >>> from dataclasses import make_dataclass
 |  >>> Point = make_dataclass("Point", [("x", int), ("y", int)])
 |  >>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
 |      x  y
 |  0  0  0
 |  1  0  3
 |  2  2  3
 |
 |  Method resolution order:
 |      DataFrame
 |      pandas.core.generic.NDFrame
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      pandas.core.base.SelectionMixin
 |      pandas.core.indexing.IndexingMixin
 |      pandas.core.arraylike.OpsMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __divmod__(self, other) -> 'Tuple[DataFrame, DataFrame]'
 |
 |  __getitem__(self, key)
 |
 |  __init__(self, data=None, index: 'Optional[Axes]' = None, columns: 'Optional[Axes]' = None, dtype: 'Optional[Dtype]' = None, copy: 'bool' = False)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __len__(self) -> 'int'
 |      Returns length of info axis, but here we use the index.
 |
 |  __matmul__(self, other)
 |      Matrix multiplication using binary `@` operator in Python>=3.5.
 |
 |  __rdivmod__(self, other) -> 'Tuple[DataFrame, DataFrame]'
 |
 |  __repr__(self) -> 'str'
 |      Return a string representation for a particular DataFrame.
 |
 |  __rmatmul__(self, other)
 |      Matrix multiplication using binary `@` operator in Python>=3.5.
 |
 |  __setitem__(self, key, value)
 |
 |  add(self, other, axis='columns', level=None, fill_value=None)
 |      Get Addition of dataframe and other, element-wise (binary operator `add`).
 |
 |      Equivalent to ``dataframe + other``, but with support to substitute a fill_value
 |      for missing data in one of the inputs. With reverse version, `radd`.
 |
 |      Among flexible wrappers (`add`, `sub`, `mul`, `div`, `mod`, `pow`) to
 |      arithmetic operators: `+`, `-`, `*`, `/`, `//`, `%`, `**`.
 |
 |      Parameters
 |      ----------
 |      other : scalar, sequence, Series, or DataFrame
 |          Any single or multiple element data structure, or list-like object.
 |      axis : {0 or 'index', 1 or 'columns'}
 |          Whether to compare by the index (0 or 'index') or columns
 |          (1 or 'columns'). For Series input, axis to match Series index on.
 |      level : int or label
 |          Broadcast across a level, matching Index values on the
 |          passed MultiIndex level.
 |      fill_value : float or None, default None
 |          Fill existing missing (NaN) values, and any new element needed for
 |          successful DataFrame alignment, with this value before computation.
 |          If data in both corresponding DataFrame locations is missing
 |          the result will be missing.
 |
 |      Returns
 |      -------
 |      DataFrame
 |          Result of the arithmetic operation.
 |
 |      See Also
 |      --------
 |      DataFrame.add : Add DataFrames.
 |      DataFrame.sub : Subtract DataFrames.
 |      DataFrame.mul : Multiply DataFrames.
 |      DataFrame.div : Divide DataFrames (float division).
 |      DataFrame.truediv : Divide DataFrames (float division).
 |      DataFrame.floordiv : Divide DataFrames (integer division).
 |      DataFrame.mod : Calculate modulo (remainder after division).
 |      DataFrame.pow : Calculate exponential power.
 |
 |      Notes
 |      -----
 |      Mismatched indices will be unioned together.
 |
 |      Examples
 |      --------
 |      >>> df = pd.DataFrame({'angles': [0, 3, 4],
 |      ...                    'degrees': [360, 180, 360]},
 |      ...                   index=['circle', 'triangle', 'rectangle'])
 |      >>> df
 |                 angles  degrees
 |      circle          0      360
 |      triangle        3      180
 |      rectangle       4      360
 |
 |      Add a scalar with operator version which return the same
 |      results.
 |
 |      >>> df + 1
 |                 angles  degrees
 |      circle          1      361
 |      triangle        4      181
 |      rectangle       5      361
 |
 |      >>> df.add(1)
 |                 angles  degrees
 |      circle          1      361
 |      triangle        4      181
 |      rectangle       5      361
 |
 |      Divide by constant with reverse version.
 |
 |      >>> df.div(10)
 |                 angles  degrees
 |      circle        0.0     36.0
 |      triangle      0.3     18.0
 |      rectangle     0.4     36.0
 |
 |      >>> df.rdiv(10)
 |                   angles   degrees
 |      circle          inf  0.027778
 |      triangle   3.333333  0.055556
 |      rectangle  2.500000  0.027778
 |
 |      Subtract a list and Series by axis with operator version.
 |
 |      >>> df - [1, 2]
 |                 angles  degrees
 |      circle         -1      358
 |      triangle        2      178
 |      rectangle       3      358
 |
 |      >>> df.sub([1, 2], axis='columns')
 |                 angles  degrees
 |      circle         -1      358
 |      triangle        2      178
 |      rectangle       3      358
 |
 |      >>> df.sub(pd.Series([1, 1, 1], index=['circle', 'triangle', 'rectangle']),
 |      ...        axis='index')
 |                 angles  degrees
 |      circle         -1      359
 |      triangle        2      179
 |      rectangle       3      359
 |
 |      Multiply a DataFrame of different shape with operator version.
 |
 |      >>> other = pd.DataFrame({'angles': [0, 3, 4]},
 |      ...                      index=['circle', 'triangle', 'rectangle'])
 |      >>> other
 |                 angles
 |      circle          0
 |      triangle        3
 |      rectangle       4
 |
 |      >>> df * other
 |                 angles  degrees
 |      circle          0      NaN
 |      triangle        9      NaN
 |      rectangle      16      NaN
 |
 |      >>> df.mul(other, fill_value=0)
 |                 angles  degrees
 |      circle          0      0.0
 |      triangle        9      0.0
 |      rectangle      16      0.0
 |
 |      Divide by a MultiIndex by level.
 |
 |      >>> df_multindex = pd.DataFrame({'angles': [0, 3, 4, 4, 5, 6],
 |      ...                              'degrees': [360, 180, 360, 360, 540, 720]},
 |      ...                             index=[['A', 'A', 'A', 'B', 'B', 'B'],
 |      ...                                    ['circle', 'triangle', 'rectangle',
 |      ...                                     'square', 'pentagon', 'hexagon']])
 |      >>> df_multindex
 |                   angles  degrees
 |      A circle          0      360
 |        triangle        3      180
 |        rectangle       4      360
 |      B square          4      360
 |        pentagon        5      540
 |        hexagon         6      720
 |
 |      >>> df.div(df_multindex, level=1, fill_value=0)
 |                   angles  degrees
 |      A circle        NaN      1.0
 |        triangle      1.0      1.0
 |        rectangle     1.0      1.0
 |      B square        0.0      0.0
 |        pentagon      0.0      0.0
 |        hexagon       0.0      0.0
 |
 |  agg = aggregate(self, func=None, axis=0, *args, **kwargs)
 |
 |  aggregate(self, func=None, axis=0, *args, **kwargs)
 |      Aggregate using one or more operations over the specified axis.
 |
 |      Parameters
 |      ----------
 |      func : function, str, list or dict
 |          Function to use for aggregating the data. If a function, must either
 |          work when passed a DataFrame or when passed to DataFrame.apply.
 |
 |          Accepted combinations are:
 |
 |          - function
 |          - string function name
 |          - list of functions and/or function names, e.g. ``[np.sum, 'mean']``
 |          - dict of axis labels -> functions, function names or list of such.
 |      axis : {0 or 'index', 1 or 'columns'}, default 0
 |              If 0 or 'index': apply function to each column.
 |              If 1 or 'columns': apply function to each row.
 |      *args
 |          Positional arguments to pass to `func`.
 |      **kwargs
 |          Keyword arguments to pass to `func`.
 |
 |      Returns
 |      -------
 |      scalar, Series or DataFrame
 |
 |          The return can be:
 |
 |          * scalar : when Series.agg is called with single function
 |          * Series : when DataFrame.agg is called with a single function
 |          * DataFrame : when DataFrame.agg is called with several functions
 |
 |          Return scalar, Series or DataFrame.
 |
 |      The aggregation operations are always performed over an axis, either the
 |      index (default) or the column axis. This behavior is different from
 |      `numpy` aggregation functions (`mean`, `median`, `prod`, `sum`, `std`,
 |      `var`), where the default is to compute the aggregation of the flattened
 |      array, e.g., ``numpy.mean(arr_2d)`` as opposed to
 |      ``numpy.mean(arr_2d, axis=0)``.
 |
 |      `agg` is an alias for `aggregate`. Use the alias.
 |
 |      See Also
 |      --------
 |      DataFrame.apply : Perform any type of operations.
 |      DataFrame.transform : Perform transformation type operations.
 |      core.groupby.GroupBy : Perform operations over groups.
 |      core.resample.Resampler : Perform operations over resampled bins.
 |      core.window.Rolling : Perform operations over rolling window.
 |      core.window.Expanding : Perform operations over expanding window.
 |      core.window.ExponentialMovingWindow : Perform operation over exponential weighted
 |          window.
 |
 |      Notes
 |      -----
 |      `agg` is an alias for `aggregate`. Use the alias.
 |
 |      A passed user-defined-function will be passed a Series for evaluation.
 |
 |      Examples
 |      --------
 |      >>> df = pd.DataFrame([[1, 2, 3],
 |      ...                    [4, 5, 6],
 |      ...                    [7, 8, 9],
 |      ...                    [np.nan, np.nan, np.nan]],
 |      ...                   columns=['A', 'B', 'C'])
 |
 |      Aggregate these functions over the rows.
 |
 |      >>> df.agg(['sum', 'min'])
 |              A     B     C
 |      sum  12.0  15.0  18.0
 |      min   1.0   2.0   3.0
 |
 |      Different aggregations per column.
 |
 |      >>> df.agg({'A' : ['sum', 'min'], 'B' : ['min', 'max']})
 |              A    B
 |      sum  12.0  NaN
 |      min   1.0  2.0
 |      max   NaN  8.0
 |
 |      Aggregate different functions over the columns and rename the index of the resulting
 |      DataFrame.
 |
 |      >>> df.agg(x=('A', max), y=('B', 'min'), z=('C', np.mean))
 |           A    B    C
 |      x  7.0  NaN  NaN
 |      y  NaN  2.0  NaN
 |      z  NaN  NaN  6.0
 |
 |      Aggregate over the columns.
 |
 |      >>> df.agg("mean", axis="columns")
 |      0    2.0
 |      1    5.0
 |      2    8.0
 |      3    NaN
 |      dtype: float64
 |
 |  align(self, other, join='outer', axis=None, level=None, copy=True, fill_value=None, method=None, limit=None, fill_axis=0, broadcast_axis=None) -> 'DataFrame'
 |      Align two objects on their axes with the specified join method.
 |
 |      Join method is specified for each axis Index.
 |
 |      Parameters
 |      ----------
 |      other : DataFrame or Series
 |      join : {'outer', 'inner', 'left', 'right'}, default 'outer'
 |      axis : allowed axis of the other object, default None
 |          Align on index (0), columns (1), or both (None).
 |      level : int or level name, default None
 |          Broadcast across a level, matching Index values on the
 |          passed MultiIndex level.
 |      copy : bool, default True
 |          Always returns new objects. If copy=False and no reindexing is
 |          required then original objects are returned.
 |      fill_value : scalar, default np.NaN
 |          Value to use for missing values. Defaults to NaN, but can be any
 |          "compatible" value.
 |      method : {'backfill', 'bfill', 'pad', 'ffill', None}, default None
 |          Method to use for filling holes in reindexed Series:
 |
 |          - pad / ffill: propagate last valid observation forward to next valid.
 |          - backfill / bfill: use NEXT valid observation to fill gap.
 |
 |      limit : int, default None
 |          If method is specified, this is the maximum number of consecutive
 |          NaN values to forward/backward fill. In other words, if there is
 |          a gap with more than this number of consecutive NaNs, it will only
 |          be partially filled. If method is not specified, this is the
 |          maximum number of entries along the entire axis where NaNs will be
 |          filled. Must be greater than 0 if not None.
 |      fill_axis : {0 or 'index', 1 or 'columns'}, default 0
 |          Filling axis, method and limit.
 |      broadcast_axis : {0 or 'index', 1 or 'columns'}, default None
 |          Broadcast values along this axis, if aligning two objects of
 |          different dimensions.
 |
 |      Returns
 |      -------
 |      (left, right) : (DataFrame, type of other)
 |          Aligned objects.
 |
 |  all(self, axis=0, bool_only=None, skipna=True, level=None, **kwargs)
 |      Return whether all elements are True, potentially over an axis.
 |
 |      Returns True unless there at least one element within a series or
 |      along a Dataframe axis that is False or equivalent (e.g. zero or
 |      empty).
 |
 |      Parameters
 |      ----------
 |      axis : {0 or 'index', 1 or 'columns', None}, default 0
 |          Indicate which axis or axes should be reduced.
 |
 |          * 0 / 'index' : reduce the index, return a Series whose index is the
 |            original column labels.
 |          * 1 / 'columns' : reduce the columns, return a Series whose index is the
 |            original index.
 |          * None : reduce all axes, return a scalar.
 |
 |      bool_only : bool, default None
 |          Include only boolean columns. If None, will attempt to use everything,
 |          then use only boolean data. Not implemented for Series.
 |      skipna : bool, default True
 |          Exclude NA/null values. If the entire row/column is NA and skipna is
 |          True, then the result will be True, as for an empty row/column.
 |          If skipna is False, then NA are treated as True, because these are not
 |          equal to zero.
 |      level : int or level name, default None
 |          If the axis is a MultiIndex (hierarchical), count along a
 |          particular level, collapsing into a Series.
 |      **kwargs : any, default None
 |          Additional keywords have no effect but might be accepted for
 |          compatibility with NumPy.
 |
 |      Returns
 |      -------
 |      Series or DataFrame
 |          If level is specified, then, DataFrame is returned; otherwise, Series
 |          is returned.
 |
 |      See Also
 |      --------
 |      Series.all : Return True if all elements are True.
 |      DataFrame.any : Return True if one (or more) elements are True.
 |
 |      Examples
 |      --------
 |      **Series**
 |
 |      >>> pd.Series([True, True]).all()
 |      True
 |      >>> pd.Series([True, False]).all()
 |      False
 |      >>> pd.Series([]).all()
 |      True
 |      >>> pd.Series([np.nan]).all()
 |      True
 |      >>> pd.Series([np.nan]).all(skipna=False)
 |      True
 |
 |      **DataFrames**
 |
 |      Create a dataframe from a dictionary.
 |
 |      >>> df = pd.DataFrame({'col1': [True, True], 'col2': [True, False]})
 |      >>> df
 |         col1   col2
 |      0  True   True
 |      1  True  False
 |
 |      Default behaviour checks if column-wise values all return True.
 |
 |      >>> df.all()
 |      col1     True
 |      col2    False
 |      dtype: bool
 |
 |      Specify ``axis='columns'`` to check if row-wise values all return True.
 |
 |      >>> df.all(axis='columns')
 |      0     True
 |      1    False
 |      dtype: bool
 |
 |      Or ``axis=None`` for whether every value is True.
 |
 |      >>> df.all(axis=None)
 |      False
 |
 |  any(self, axis=0, bool_only=None, skipna=True, level=None, **kwargs)
 |      Return whether any element is True, potentially over an axis.
 |
 |      Returns False unless there is at least one element within a series or
 |      along a Dataframe axis that is True or equivalent (e.g. non-zero or
 |      non-empty).
 |
 |      Parameters
 |      ----------
 |      axis : {0 or 'index', 1 or 'columns', None}, default 0
 |          Indicate which axis or axes should be reduced.
 |
 |          * 0 / 'index' : reduce the index, return a Series whose index is the
 |            original column labels.
 |          * 1 / 'columns' : reduce the columns, return a Series whose index is the
 |            original index.
 |          * None : reduce all axes, return a scalar.
 |
 |      bool_only : bool, default None
 |          Include only boolean columns. If None, will attempt to use everything,
 |          then use only boolean data. Not implemented for Series.
 |      skipna : bool, default True
 |          Exclude NA/null values. If the entire row/column is NA and skipna is
 |          True, then the result will be False, as for an empty row/column.
 |          If skipna is False, then NA are treated as True, because these are not
 |          equal to zero.
 |      level : int or level name, default None
 |          If the axis is a MultiIndex (hierarchical), count along a
 |          particular level, collapsing into a Series.

In [136]:
# We're going to read another data set in with more variety
logons_full_df = pd.read_pickle("./data/host_logons.pkl")
net_full_df = pd.read_pickle("./data/az_net_comms_df.pkl")

# also create a demo version with just 3 rows
logons_df = logons_full_df.sample(20)
logons_df.head(5)

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
99,52b1ab41-869e-4138-9e40-2a4457f09bf0,Window Manager\DWM-2,4624,2019-02-12 22:22:21.240,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,DWM-2,Window Manager,S-1-5-90-0-2,0x106b458,Advapi,2,Negotiate,,-,-,2019-02-12 22:22:21.240
89,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-14 04:20:55.763,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-14 04:20:55.763
32,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 06:42:08.110,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 06:42:08.110
3,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:38:16.550,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc912d62,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:38:16.550
123,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 20:39:14.110,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 20:39:14.110

### Rows and Columns of a DataFrame are pandas *Series*

In [9]:
print(type(logons_df.iloc[0]))

<class 'pandas.core.series.Series'>

In [12]:
print("logons_df", type(logons_df))
print("logons_df.Account", type(logons_df.Account)) # "Account" row
print("logons_df.iloc[0])", type(logons_df.iloc[0])) # First row

# At the intersection of a row and column we get a simple type - the cell content
print("logons_df.iloc[0].Account", type(logons_df.iloc[0].Account), logons_df.iloc[0].Account)

logons_df <class 'pandas.core.frame.DataFrame'>
logons_df.Account <class 'pandas.core.series.Series'>
logons_df.iloc[0]) <class 'pandas.core.series.Series'>
logons_df.iloc[0].Account <class 'str'> NT AUTHORITY\SYSTEM

### What does a series look like?

In [ ]:
# Column
logons_df.Account

In [14]:
# Row
logons_df.iloc[0]

TenantId                     52b1ab41-869e-4138-9e40-2a4457f09bf0
Account                                       NT AUTHORITY\SYSTEM
EventID                                                      4624
TimeGenerated                          2019-02-12 04:56:34.307000
SourceComputerId             263a788b-6526-4cdc-8ed9-d79402fe4aa0
Computer                                          MSTICAlertsWin1
SubjectUserName                                  MSTICAlertsWin1$
SubjectDomainName                                       WORKGROUP
SubjectUserSid                                           S-1-5-18
TargetUserName                                             SYSTEM
TargetDomainName                                     NT AUTHORITY
TargetUserSid                                            S-1-5-18
TargetLogonId                                               0x3e7
LogonProcessName                                         Advapi
LogonType                                                       5
AuthenticationPackageName                               Negotiate
Status
IpAddress                                                       -
WorkstationName                                                 -
TimeCreatedUtc                         2019-02-12 04:56:34.307000
Name: 0, dtype: object

## Selecting Columns

Selecting a single column

In [13]:
logons_df.Account

0           NT AUTHORITY\SYSTEM
1    MSTICAlertsWin1\MSTICAdmin
2    MSTICAlertsWin1\MSTICAdmin
3    MSTICAlertsWin1\MSTICAdmin
4    MSTICAlertsWin1\MSTICAdmin
5           NT AUTHORITY\SYSTEM
6           NT AUTHORITY\SYSTEM
7           NT AUTHORITY\SYSTEM
8           NT AUTHORITY\SYSTEM
9           NT AUTHORITY\SYSTEM
Name: Account, dtype: object

More general syntax and mandatory if column name has spaces or other illegal chars (like ".")

In [ ]:
logons_df["Account"]

To select multiple columns you use a Python list

In [ ]:
my_cols = ["Account", "TimeGenerated"]
logons_df[my_cols]

In [92]:
# Or just
logons_df[["Account", "TimeGenerated"]]

                         Account           TimeGenerated
0            NT AUTHORITY\SYSTEM 2019-02-12 04:56:34.307
1     MSTICAlertsWin1\MSTICAdmin 2019-02-12 04:37:25.340
2     MSTICAlertsWin1\MSTICAdmin 2019-02-12 04:37:27.997
3     MSTICAlertsWin1\MSTICAdmin 2019-02-12 04:38:16.550
4     MSTICAlertsWin1\MSTICAdmin 2019-02-12 04:38:21.370
5            NT AUTHORITY\SYSTEM 2019-02-12 04:50:09.713
6            NT AUTHORITY\SYSTEM 2019-02-12 04:50:18.660
7            NT AUTHORITY\SYSTEM 2019-02-12 04:43:56.327
8            NT AUTHORITY\SYSTEM 2019-02-12 04:44:10.343
9            NT AUTHORITY\SYSTEM 2019-02-12 04:40:11.867
10             NT AUTHORITY\IUSR 2019-02-12 04:40:12.360
11           NT AUTHORITY\SYSTEM 2019-02-12 04:40:52.343
12           NT AUTHORITY\SYSTEM 2019-02-12 04:40:03.870
13           NT AUTHORITY\SYSTEM 2019-02-12 04:40:04.083
14  NT AUTHORITY\NETWORK SERVICE 2019-02-12 04:40:04.207
15          Window Manager\DWM-1 2019-02-12 04:40:04.483
16          Window Manager\DWM-1 2019-02-12 04:40:04.483
17    NT AUTHORITY\LOCAL SERVICE 2019-02-12 04:40:04.573
18           NT AUTHORITY\SYSTEM 2019-02-12 04:40:04.997
19           NT AUTHORITY\SYSTEM 2019-02-12 04:40:05.093

### Use the columns property to get the column names

In [ ]:
logons_df.columns

In [ ]:
logons_df[[]]

## Indexes - brief introduction

In [20]:
logons_df.index

RangeIndex(start=0, stop=10, step=1)

In [21]:
# Access a row at an index location
logons_df.loc[3]

TenantId                             52b1ab41-869e-4138-9e40-2a4457f09bf0
Account                                        MSTICAlertsWin1\MSTICAdmin
EventID                                                              4624
TimeGenerated                                  2019-02-12 04:38:16.550000
SourceComputerId                     263a788b-6526-4cdc-8ed9-d79402fe4aa0
Computer                                                  MSTICAlertsWin1
SubjectUserName                                                         -
SubjectDomainName                                                       -
SubjectUserSid                                                    S-1-0-0
TargetUserName                                                 MSTICAdmin
TargetDomainName                                          MSTICAlertsWin1
TargetUserSid                S-1-5-21-996632719-2361334927-4038480536-500
TargetLogonId                                                   0xc912d62
LogonProcessName                                                 NtLmSsp
LogonType                                                               3
AuthenticationPackageName                                            NTLM
Status
IpAddress                                                 131.107.147.209
WorkstationName                                            IANHELLE-DEV17
TimeCreatedUtc                                 2019-02-12 04:38:16.550000
Name: 3, dtype: object

In [22]:
# Access a row at a physical row location
logons_df.iloc[3]

TenantId                             52b1ab41-869e-4138-9e40-2a4457f09bf0
Account                                        MSTICAlertsWin1\MSTICAdmin
EventID                                                              4624
TimeGenerated                                  2019-02-12 04:38:16.550000
SourceComputerId                     263a788b-6526-4cdc-8ed9-d79402fe4aa0
Computer                                                  MSTICAlertsWin1
SubjectUserName                                                         -
SubjectDomainName                                                       -
SubjectUserSid                                                    S-1-0-0
TargetUserName                                                 MSTICAdmin
TargetDomainName                                          MSTICAlertsWin1
TargetUserSid                S-1-5-21-996632719-2361334927-4038480536-500
TargetLogonId                                                   0xc912d62
LogonProcessName                                                 NtLmSsp
LogonType                                                               3
AuthenticationPackageName                                            NTLM
Status
IpAddress                                                 131.107.147.209
WorkstationName                                            IANHELLE-DEV17
TimeCreatedUtc                                 2019-02-12 04:38:16.550000
Name: 3, dtype: object

In [24]:
indexed_logons_df = logons_df.set_index("Account")
display(logons_df.head(3))
display(indexed_logons_df.head(3))

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
0,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:56:34.307,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:56:34.307
1,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:25.340,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90e957,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:25.340
2,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:27.997,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90ea44,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:27.997

,TenantId,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
Account,,,,,,,,,,,,,,,,,,,
NT AUTHORITY\SYSTEM,52b1ab41-869e-4138-9e40-2a4457f09bf0,4624,2019-02-12 04:56:34.307,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:56:34.307
MSTICAlertsWin1\MSTICAdmin,52b1ab41-869e-4138-9e40-2a4457f09bf0,4624,2019-02-12 04:37:25.340,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90e957,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:25.340
MSTICAlertsWin1\MSTICAdmin,52b1ab41-869e-4138-9e40-2a4457f09bf0,4624,2019-02-12 04:37:27.997,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90ea44,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:27.997

In [47]:
indexed_logons_df.loc["NT AUTHORITY\\SYSTEM"].head()

,TenantId,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
Account,,,,,,,,,,,,,,,,,,,
NT AUTHORITY\SYSTEM,52b1ab41-869e-4138-9e40-2a4457f09bf0,4624,2019-02-12 04:56:34.307,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:56:34.307
NT AUTHORITY\SYSTEM,52b1ab41-869e-4138-9e40-2a4457f09bf0,4624,2019-02-12 04:50:09.713,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:50:09.713
NT AUTHORITY\SYSTEM,52b1ab41-869e-4138-9e40-2a4457f09bf0,4624,2019-02-12 04:50:18.660,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:50:18.660
NT AUTHORITY\SYSTEM,52b1ab41-869e-4138-9e40-2a4457f09bf0,4624,2019-02-12 04:43:56.327,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:43:56.327
NT AUTHORITY\SYSTEM,52b1ab41-869e-4138-9e40-2a4457f09bf0,4624,2019-02-12 04:44:10.343,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:44:10.343

In [48]:
# Physical row indexing works as before
indexed_logons_df.iloc[3]

TenantId                             52b1ab41-869e-4138-9e40-2a4457f09bf0
EventID                                                              4624
TimeGenerated                                  2019-02-12 04:38:16.550000
SourceComputerId                     263a788b-6526-4cdc-8ed9-d79402fe4aa0
Computer                                                  MSTICAlertsWin1
SubjectUserName                                                         -
SubjectDomainName                                                       -
SubjectUserSid                                                    S-1-0-0
TargetUserName                                                 MSTICAdmin
TargetDomainName                                          MSTICAlertsWin1
TargetUserSid                S-1-5-21-996632719-2361334927-4038480536-500
TargetLogonId                                                   0xc912d62
LogonProcessName                                                 NtLmSsp
LogonType                                                               3
AuthenticationPackageName                                            NTLM
Status
IpAddress                                                 131.107.147.209
WorkstationName                                            IANHELLE-DEV17
TimeCreatedUtc                                 2019-02-12 04:38:16.550000
Name: MSTICAlertsWin1\MSTICAdmin, dtype: object

## Accessing individual values

In [40]:
print("iloc + named column", logons_df.iloc[0].Account)
print("at - row idx + named column", logons_df.at[0, "Account"])
print("iat - row idx + column idx", logons_df.iat[0, 1])


print("\nBut if the index is not unique 'at' returns a series\n")

print(
    "at - row idx + named column",
    "Type:",
    type(indexed_logons_df.at["NT AUTHORITY\\SYSTEM", "EventID"]),
    "Result:",
    indexed_logons_df.at["NT AUTHORITY\\SYSTEM", "EventID"],
    sep="\n",
)

iloc + named column NT AUTHORITY\SYSTEM
at - row idx + named column NT AUTHORITY\SYSTEM
iat - row idx + column idx NT AUTHORITY\SYSTEM

But if the index is not unique 'at' returns a series

at - row idx + named column
Type:
<class 'pandas.core.series.Series'>
Result:
Account
NT AUTHORITY\SYSTEM    4624
NT AUTHORITY\SYSTEM    4624
NT AUTHORITY\SYSTEM    4624
NT AUTHORITY\SYSTEM    4624
NT AUTHORITY\SYSTEM    4624
NT AUTHORITY\SYSTEM    4624
Name: EventID, dtype: int64

# Selecting/Searching

## Specific row by number

In [49]:
logons_df.iloc[2].Account

'MSTICAlertsWin1\\MSTICAdmin'

In [55]:
logons_df.iloc[3:6]

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
3,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:38:16.550,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc912d62,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:38:16.550
4,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:38:21.370,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc913737,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:38:21.370
5,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:50:09.713,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:50:09.713

In [56]:
logons_df.head(5) == logons_df.iloc[0:5]

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

## Select by content - Boolean expression

- ==
- !=
- \>, <, >=, <=

In [67]:
logons_df["Account"] == "MSTICAlertsWin1\\MSTICAdmin"

0     False
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: Account, dtype: bool

### Use boolean result of expression to filter DataFrame

In [69]:
logons_df.loc[logons_df["Account"] == "MSTICAlertsWin1\\MSTICAdmin"]

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
1,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:25.340,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90e957,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:25.340
2,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:27.997,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90ea44,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:27.997
3,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:38:16.550,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc912d62,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:38:16.550
4,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:38:21.370,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc913737,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:38:21.370

## Other operators with boolean indexing

Operators vary depending on data type!!!

In [70]:
logons_df.dtypes

TenantId                             object
Account                              object
EventID                               int64
TimeGenerated                datetime64[ns]
SourceComputerId                     object
Computer                             object
SubjectUserName                      object
SubjectDomainName                    object
SubjectUserSid                       object
TargetUserName                       object
TargetDomainName                     object
TargetUserSid                        object
TargetLogonId                        object
LogonProcessName                     object
LogonType                             int64
AuthenticationPackageName            object
Status                               object
IpAddress                            object
WorkstationName                      object
TimeCreatedUtc               datetime64[ns]
dtype: object

In [71]:
logons_df[logons_df["Account"].endswith("MSTICAdmin")]

AttributeError: 'Series' object has no attribute 'endswith'

In [72]:
logons_df["Account"]

0              NT AUTHORITY\SYSTEM
1       MSTICAlertsWin1\MSTICAdmin
2       MSTICAlertsWin1\MSTICAdmin
3       MSTICAlertsWin1\MSTICAdmin
4       MSTICAlertsWin1\MSTICAdmin
5              NT AUTHORITY\SYSTEM
6              NT AUTHORITY\SYSTEM
7              NT AUTHORITY\SYSTEM
8              NT AUTHORITY\SYSTEM
9              NT AUTHORITY\SYSTEM
10               NT AUTHORITY\IUSR
11             NT AUTHORITY\SYSTEM
12             NT AUTHORITY\SYSTEM
13             NT AUTHORITY\SYSTEM
14    NT AUTHORITY\NETWORK SERVICE
15            Window Manager\DWM-1
16            Window Manager\DWM-1
17      NT AUTHORITY\LOCAL SERVICE
18             NT AUTHORITY\SYSTEM
19             NT AUTHORITY\SYSTEM
Name: Account, dtype: object

### We need to tell pandas to treat the series as a string
(a bit like tostring(dynamic) in KQL)

logons_df[logons_df["Account"].**str**.contains("MSTICAdmin")]

In [73]:
logons_df[logons_df["Account"].str.endswith("MSTICAdmin")]

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
1,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:25.340,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90e957,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:25.340
2,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:27.997,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90ea44,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:27.997
3,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:38:16.550,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc912d62,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:38:16.550
4,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:38:21.370,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc913737,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:38:21.370

## Multiple conditions
```
& == AND
| == OR
~ == NOT
```

*Always use parentheses around individual expressions in composite logical expressions!*

In [ ]:
logons_df[
    logons_df["Account"].str.contains("MSTICAdmin")
]

In [79]:
t1 = pd.Timestamp("2019-02-12 04:37:25")
t2 = pd.to_datetime("2019-02-12 04:37:26")
t1, t2

(Timestamp('2019-02-12 04:37:25'), Timestamp('2019-02-12 04:37:26'))

In [80]:
logons_df[
    (logons_df["Account"].str.contains("MSTICAdmin"))
    &
    (logons_df["TimeGenerated"] >= t1)
    &
    (logons_df["TimeGenerated"] <= t2)
]

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
1,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:25.340,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90e957,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:25.340

In [82]:
logons_df[
    ~(logons_df["Account"].str.contains("MSTICAdmin"))
    &
    (logons_df["TimeGenerated"] >= t2)
].head(5)

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
0,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:56:34.307,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:56:34.307
5,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:50:09.713,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:50:09.713
6,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:50:18.660,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:50:18.660
7,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:43:56.327,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:43:56.327
8,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:44:10.343,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:44:10.343

In [78]:
logons_df[
    (logons_df["LogonType"] == 3)
    &
    (logons_df["TimeGenerated"].dt.hour == 4)
    &
    (logons_df["TimeGenerated"].dt.minute == 37)
]

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
1,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:25.340,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90e957,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:25.340
2,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:27.997,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90ea44,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:27.997

### Boolean indexes are Pandas series - you can save and re-use

In [86]:
logon_type_3 = logons_df["LogonType"] == 3
hour_4 = logons_df["TimeGenerated"].dt.hour == 4
minute_37 = logons_df["TimeGenerated"].dt.minute == 37

logons_df[logon_type_3 & hour_4 & minute_37]

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
1,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:25.340,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90e957,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:25.340
2,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:27.997,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90ea44,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:27.997

### Pandas `str` and `dt` (datetime) accessor functions

In [83]:
str_funcs = [func for func in dir(logons_df["Account"].str) if not func.startswith("_")]
print("Pandas 'str' functions")
print("----------------------")
print(", ".join(str_funcs))
print("\nRead more here")
print("https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html#method-summary")
dt_funcs = [func for func in dir(logons_df["TimeGenerated"].dt) if not func.startswith("_")]
print("\nPandas 'dt' (datetime) functions")
print("----------------------------------")
print(", ".join(dt_funcs))

Pandas 'str' functions
----------------------
capitalize, casefold, cat, center, contains, count, decode, encode, endswith, extract, extractall, find, findall, fullmatch, get, get_dummies, index, isalnum, isalpha, isdecimal, isdigit, islower, isnumeric, isspace, istitle, isupper, join, len, ljust, lower, lstrip, match, normalize, pad, partition, repeat, replace, rfind, rindex, rjust, rpartition, rsplit, rstrip, slice, slice_replace, split, startswith, strip, swapcase, title, translate, upper, wrap, zfill

Read more here
https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html#method-summary

Pandas 'dt' (datetime) functions
----------------------------------
ceil, date, day, day_name, day_of_week, day_of_year, dayofweek, dayofyear, days_in_month, daysinmonth, floor, freq, hour, is_leap_year, is_month_end, is_month_start, is_quarter_end, is_quarter_start, is_year_end, is_year_start, isocalendar, microsecond, minute, month, month_name, nanosecond, normalize, quarter, round, second, strftime, time, timetz, to_period, to_pydatetime, tz, tz_convert, tz_localize, week, weekday, weekofyear, year

## `isin` operator/function

In [ ]:
logons_df[logons_df["TargetUserName"].isin(["MSTICAdmin", "SYSTEM"])]

## query function
Useful for simpler queries - and definitely nicer-looking but some limitations - only simple operators supported.

Good for quick things but I prefer the boolean stuff for more complex queries.

To reference Python variables prefix the variable name with "@" (see second example)

In [87]:
logons_df.query("TargetUserName == 'MSTICAdmin' and TargetLogonId == '0xc90ea44'")

logons_df.query("TargetUserName == 'MSTICAdmin' and TargetLogonId == '0xc90ea44' and TimeGenerated > @t2")

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
2,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:27.997,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90ea44,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:27.997

In [90]:
(
    logons_df
    .query("TargetLogonId == '0xc90ea44' and TimeGenerated > @t2")
    [logons_df["Account"].str.match("MST.*")]
)

C:\Users\Ian\Anaconda3\envs\condadev\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
2,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:27.997,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90ea44,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:27.997

## Combing Column Select and Query

In [91]:
(
    logons_df[logons_df["Account"].str.contains("MSTICAdmin")]
    [["Account", "TimeGenerated"]]
)

                      Account           TimeGenerated
1  MSTICAlertsWin1\MSTICAdmin 2019-02-12 04:37:25.340
2  MSTICAlertsWin1\MSTICAdmin 2019-02-12 04:37:27.997
3  MSTICAlertsWin1\MSTICAdmin 2019-02-12 04:38:16.550
4  MSTICAlertsWin1\MSTICAdmin 2019-02-12 04:38:21.370

### and with column rename

In [ ]:
(
    logons_df[logons_df["Account"].str.contains("MSTICAdmin")]
    [["Account", "TimeGenerated"]]
    .rename(columns={"Account": "User", "TimeGenerated": "Time"})
)

# Sorting and removing duplicates

In [122]:
logons_df.sort_values("TimeGenerated", ascending=False).head(3)

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
0,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:56:34.307,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:56:34.307
6,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:50:18.660,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:50:18.660
5,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:50:09.713,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:50:09.713

In [126]:
(
    logons_df[["Account", "LogonType"]]
    .drop_duplicates()
    .sort_values("Account")
)

                         Account  LogonType
1     MSTICAlertsWin1\MSTICAdmin          3
10             NT AUTHORITY\IUSR          5
17    NT AUTHORITY\LOCAL SERVICE          5
14  NT AUTHORITY\NETWORK SERVICE          5
0            NT AUTHORITY\SYSTEM          5
12           NT AUTHORITY\SYSTEM          0
15          Window Manager\DWM-1          2

# Grouping and Aggregation
<p style="color: white; background-color: green; text-align: center">New</p>

In [94]:
logons_df.groupby("Account")

### You need an aggregator (or iterator) make use of grouping

In [95]:
logons_df.groupby("Account").count() # Yuk!

,TenantId,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
Account,,,,,,,,,,,,,,,,,,,
MSTICAlertsWin1\MSTICAdmin,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
NT AUTHORITY\IUSR,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
NT AUTHORITY\LOCAL SERVICE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
NT AUTHORITY\NETWORK SERVICE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
NT AUTHORITY\SYSTEM,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
Window Manager\DWM-1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2

In [96]:
(
    logons_df[["TimeGenerated", "Account"]]
    .groupby("Account")
    .count()
    .rename(columns={"TimeGenerated": "Count"})
)

                              Count
Account
MSTICAlertsWin1\MSTICAdmin        4
NT AUTHORITY\IUSR                 1
NT AUTHORITY\LOCAL SERVICE        1
NT AUTHORITY\NETWORK SERVICE      1
NT AUTHORITY\SYSTEM              11
Window Manager\DWM-1              2

In [107]:
for name, logon_group in logons_df.groupby("Account"):
    print(name, type(logon_group), "size", logon_group.shape)

print("\nCollect in dictionary")
df_dict = {name: df for name, df in logons_df.groupby("Account")}

[print(f"{name}: df") for name in df_dict]

MSTICAlertsWin1\MSTICAdmin <class 'pandas.core.frame.DataFrame'> size (4, 20)
NT AUTHORITY\IUSR <class 'pandas.core.frame.DataFrame'> size (1, 20)
NT AUTHORITY\LOCAL SERVICE <class 'pandas.core.frame.DataFrame'> size (1, 20)
NT AUTHORITY\NETWORK SERVICE <class 'pandas.core.frame.DataFrame'> size (1, 20)
NT AUTHORITY\SYSTEM <class 'pandas.core.frame.DataFrame'> size (11, 20)
Window Manager\DWM-1 <class 'pandas.core.frame.DataFrame'> size (2, 20)

Collect in dictionary
MSTICAlertsWin1\MSTICAdmin: df
NT AUTHORITY\IUSR: df
NT AUTHORITY\LOCAL SERVICE: df
NT AUTHORITY\NETWORK SERVICE: df
NT AUTHORITY\SYSTEM: df
Window Manager\DWM-1: df

[None, None, None, None, None, None]

## Grouping with Multiple aggregation functions

In [ ]:
(
    logons_df[["TimeGenerated", "EventID", "Account"]]
    .groupby("Account")
    .agg({"TimeGenerated": "max", "EventID": "sum"})
    .rename(columns={"TimeGenerated": "LastTime"})
)

                                            LastTime  EventID
Account
MSTICAlertsWin1\MSTICAdmin   2019-02-15 03:57:02.593    83232
MSTICAlertsWin1\ian          2019-02-15 03:56:34.440    36992
NT AUTHORITY\IUSR            2019-02-14 04:20:56.110     9248
NT AUTHORITY\LOCAL SERVICE   2019-02-14 04:20:54.803     9248
NT AUTHORITY\NETWORK SERVICE 2019-02-14 04:20:54.630     9248
NT AUTHORITY\SYSTEM          2019-02-15 11:51:37.597   564128
Window Manager\DWM-1         2019-02-14 04:20:54.773    18496
Window Manager\DWM-2         2019-02-15 03:57:01.903    27744

## Grouping with multiple columns

In [115]:
(
    logons_full_df[["TimeGenerated", "EventID", "Account", "LogonType"]]      # DF input fields
    .groupby(["Account", "LogonType"])                                        # Grouping fields
    .agg({"TimeGenerated": "max", "EventID": "count"})                        # aggregate operations
    .rename(columns={"TimeGenerated": "LastTime", "EventID": "Count"})        # Rename output
)

                                                      LastTime  Count
Account                      LogonType
MSTICAlertsWin1\MSTICAdmin   3         2019-02-15 03:57:00.207      8
                             4         2019-02-14 11:51:37.603      8
                             10        2019-02-15 03:57:02.593      2
MSTICAlertsWin1\ian          2         2019-02-12 20:29:51.030      2
                             3         2019-02-15 03:56:34.440      5
                             4         2019-02-12 20:41:17.310      1
NT AUTHORITY\IUSR            5         2019-02-14 04:20:56.110      2
NT AUTHORITY\LOCAL SERVICE   5         2019-02-14 04:20:54.803      2
NT AUTHORITY\NETWORK SERVICE 5         2019-02-14 04:20:54.630      2
NT AUTHORITY\SYSTEM          0         2019-02-14 04:20:54.370      2
                             5         2019-02-15 11:51:37.597    120
Window Manager\DWM-1         2         2019-02-14 04:20:54.773      4
Window Manager\DWM-2         2         2019-02-15 03:57:01.903      6

## Using pd.Grouper to group by time interval

In [118]:
(
    logons_full_df[["TimeGenerated", "EventID", "Account", "LogonType"]]
    .groupby(["Account", pd.Grouper(key="TimeGenerated", freq="1D")])
    .agg({"TimeGenerated": "max", "EventID": "count"})
    .rename(columns={"TimeGenerated": "LastTime", "EventID": "Count"})
)

                                                          LastTime  Count
Account                      TimeGenerated
MSTICAlertsWin1\MSTICAdmin   2019-02-09    2019-02-09 23:26:47.700      1
                             2019-02-11    2019-02-11 22:47:53.750      4
                             2019-02-12    2019-02-12 20:19:44.767      7
                             2019-02-13    2019-02-13 23:07:23.823      2
                             2019-02-14    2019-02-14 11:51:37.603      1
                             2019-02-15    2019-02-15 03:57:02.593      3
MSTICAlertsWin1\ian          2019-02-12    2019-02-12 20:41:17.310      3
                             2019-02-13    2019-02-13 00:57:37.187      3
                             2019-02-15    2019-02-15 03:56:34.440      2
NT AUTHORITY\IUSR            2019-02-12    2019-02-12 04:40:12.360      1
                             2019-02-14    2019-02-14 04:20:56.110      1
NT AUTHORITY\LOCAL SERVICE   2019-02-12    2019-02-12 04:40:04.573      1
                             2019-02-14    2019-02-14 04:20:54.803      1
NT AUTHORITY\NETWORK SERVICE 2019-02-12    2019-02-12 04:40:04.207      1
                             2019-02-14    2019-02-14 04:20:54.630      1
NT AUTHORITY\SYSTEM          2019-02-09    2019-02-09 12:35:51.683      2
                             2019-02-10    2019-02-10 21:47:21.503     11
                             2019-02-11    2019-02-11 09:59:02.593      2
                             2019-02-12    2019-02-12 22:20:59.200     53
                             2019-02-13    2019-02-13 22:08:46.537     10
                             2019-02-14    2019-02-14 14:51:37.637     33
                             2019-02-15    2019-02-15 11:51:37.597     11
Window Manager\DWM-1         2019-02-12    2019-02-12 04:40:04.483      2
                             2019-02-14    2019-02-14 04:20:54.773      2
Window Manager\DWM-2         2019-02-12    2019-02-12 22:22:21.240      4
                             2019-02-15    2019-02-15 03:57:01.903      2

# Adding and removing columns

In [148]:
new_df = logons_df.copy()

# Adding a static value
new_df["StaticValue"] = "A logon"
# Extracting a substring (there are several ways to do this)
new_df["NTDomain"] = new_df.Account.str.split("\\", 1, expand=True)[0]
# Transforming using an accessor
new_df["DayOfWeek"] = new_df.TimeGenerated.dt.day_name()
# Arithmetic calculations
new_df["BigEventID"] = new_df.EventID * 1000000
new_df["SameTimeTomorrow"] = new_df.TimeGenerated + pd.Timedelta("1D")

new_df[[
    "Account", "TimeGenerated", "StaticValue", "NTDomain", "DayOfWeek", "BigEventID", "SameTimeTomorrow"
]].head()

,Account,TimeGenerated,StaticValue,NTDomain,DayOfWeek,BigEventID,SameTimeTomorrow
99,Window Manager\DWM-2,2019-02-12 22:22:21.240,A logon,Window Manager,Tuesday,4624000000,2019-02-13 22:22:21.240
89,NT AUTHORITY\SYSTEM,2019-02-14 04:20:55.763,A logon,NT AUTHORITY,Thursday,4624000000,2019-02-15 04:20:55.763
32,NT AUTHORITY\SYSTEM,2019-02-12 06:42:08.110,A logon,NT AUTHORITY,Tuesday,4624000000,2019-02-13 06:42:08.110
3,MSTICAlertsWin1\MSTICAdmin,2019-02-12 04:38:16.550,A logon,MSTICAlertsWin1,Tuesday,4624000000,2019-02-13 04:38:16.550
123,NT AUTHORITY\SYSTEM,2019-02-12 20:39:14.110,A logon,NT AUTHORITY,Tuesday,4624000000,2019-02-13 20:39:14.110

In [138]:
new_df[["Account", "TimeGenerated", "StaticValue", "NTDomain", "DayOfWeek"]].drop(columns=["NTDomain"])

,Account,TimeGenerated,StaticValue,DayOfWeek
99,Window Manager\DWM-2,2019-02-12 22:22:21.240,A logon,Tuesday
89,NT AUTHORITY\SYSTEM,2019-02-14 04:20:55.763,A logon,Thursday
32,NT AUTHORITY\SYSTEM,2019-02-12 06:42:08.110,A logon,Tuesday
3,MSTICAlertsWin1\MSTICAdmin,2019-02-12 04:38:16.550,A logon,Tuesday
123,NT AUTHORITY\SYSTEM,2019-02-12 20:39:14.110,A logon,Tuesday
47,NT AUTHORITY\SYSTEM,2019-02-10 00:48:31.607,A logon,Sunday
45,NT AUTHORITY\SYSTEM,2019-02-10 20:03:57.417,A logon,Sunday
1,MSTICAlertsWin1\MSTICAdmin,2019-02-12 04:37:25.340,A logon,Tuesday
81,NT AUTHORITY\SYSTEM,2019-02-14 04:20:55.503,A logon,Thursday
158,Window Manager\DWM-2,2019-02-15 03:57:01.903,A logon,Friday
106,NT AUTHORITY\SYSTEM,2019-02-13 03:15:18.813,A logon,Wednesday
0,NT AUTHORITY\SYSTEM,2019-02-12 04:56:34.307,A logon,Tuesday
46,NT AUTHORITY\SYSTEM,2019-02-10 05:10:54.300,A logon,Sunday
27,NT AUTHORITY\SYSTEM,2019-02-12 04:40:11.567,A logon,Tuesday
72,NT AUTHORITY\NETWORK SERVICE,2019-02-14 04:20:54.630,A logon,Thursday
60,NT AUTHORITY\SYSTEM,2019-02-14 03:00:42.233,A logon,Thursday
6,NT AUTHORITY\SYSTEM,2019-02-12 04:50:18.660,A logon,Tuesday
144,NT AUTHORITY\SYSTEM,2019-02-12 21:58:50.563,A logon,Tuesday
66,NT AUTHORITY\SYSTEM,2019-02-14 04:21:45.410,A logon,Thursday
87,NT AUTHORITY\SYSTEM,2019-02-14 04:20:55.687,A logon,Thursday

## Some other quick ways of filtering out (in) columns

In [139]:
logons_df.filter(regex="Target.*", axis=1).head()

,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId
99,DWM-2,Window Manager,S-1-5-90-0-2,0x106b458
89,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7
32,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7
3,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc912d62
123,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7

In [146]:
logons_df.select_dtypes(include="datetime").head()  # also "number", "object"

              TimeGenerated          TimeCreatedUtc
99  2019-02-12 22:22:21.240 2019-02-12 22:22:21.240
89  2019-02-14 04:20:55.763 2019-02-14 04:20:55.763
32  2019-02-12 06:42:08.110 2019-02-12 06:42:08.110
3   2019-02-12 04:38:16.550 2019-02-12 04:38:16.550
123 2019-02-12 20:39:14.110 2019-02-12 20:39:14.110

# Cleaning Data

- Nans
- Transforming
- Reshaping

# Simple Joins

(relational joins tomorrow)

In [166]:
df1 = logons_full_df[0:10]
df2 = logons_full_df[100:110]

print("df1:", df1.shape, "df2:", df2.shape)
df1.head(3)

df1: (10, 20) df2: (10, 20)

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
0,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:56:34.307,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:56:34.307
1,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:25.340,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90e957,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:25.340
2,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:27.997,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90ea44,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:27.997

In [168]:
joined_df = pd.concat([df1, df2])

print(joined_df.shape)
joined_df

(20, 20)

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
0,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:56:34.307,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:56:34.307
1,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:25.340,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90e957,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:25.340
2,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:37:27.997,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90ea44,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:37:27.997
3,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:38:16.550,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc912d62,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:38:16.550
4,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\MSTICAdmin,4624,2019-02-12 04:38:21.370,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc913737,NtLmSsp,3,NTLM,,131.107.147.209,IANHELLE-DEV17,2019-02-12 04:38:21.370
5,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:50:09.713,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:50:09.713
6,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:50:18.660,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:50:18.660
7,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:43:56.327,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:43:56.327
8,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:44:10.343,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:44:10.343
9,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 04:40:11.867,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 04:40:11.867
100,52b1ab41-869e-4138-9e40-2a4457f09bf0,Window Manager\DWM-2,4624,2019-02-12 22:22:21.240,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,DWM-2,Window Manager,S-1-5-90-0-2,0x106b46b,Advapi,2,Negotiate,,-,-,2019-02-12 22:22:21.240
101,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-13 00:57:06.550,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-13 00:57:06.550
102,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\ian,4624,2019-02-13 00:57:19.930,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,ian,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-1120,0x15a1d83,NtLmSsp,3,NTLM,,10.0.3.4,MSTICALERTSLXVM2,2019-02-13 00:57:19.930
103,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\ian,4624,2019-02-13 00:57:37.187,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,ian,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-1120,0x15a26d7,NtLmSsp,3,NTLM,,10.0.3.4,MSTICALERTSLXVM2,2019-02-13 00:57:37.187
104,52b1ab41-869e-4138-9e40-2a4457f09bf0,MSTICAlertsWin1\ian,4624,2019-02-13 00:55:38.670,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,-,-,S-1-0-0,ian,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-1120,0x158943d,NtLmSsp,3,NTLM,,10.0.3.4,MSTICALERTSLXVM2,2019-02-13 00:55:38.670
105,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-13 04:44:32.913,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-13 04:44:32.913
106,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-13 03:15:18.813,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-13 03:15:18.813
107,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-13 20:08:47.880,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-13 20:08:47.880
108,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 21:53:36.280,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 21:53:36.280
109,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 21:53:53.453,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 21:53:53.453

In [172]:
df_list = [df1] * 3 + [df2] * 5
joined_df = pd.concat(df_list, ignore_index=True)

print(joined_df.shape)
joined_df.tail(5)

(80, 20)

,TenantId,Account,EventID,TimeGenerated,SourceComputerId,Computer,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId,LogonProcessName,LogonType,AuthenticationPackageName,Status,IpAddress,WorkstationName,TimeCreatedUtc
75,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-13 04:44:32.913,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-13 04:44:32.913
76,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-13 03:15:18.813,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-13 03:15:18.813
77,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-13 20:08:47.880,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-13 20:08:47.880
78,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 21:53:36.280,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 21:53:36.280
79,52b1ab41-869e-4138-9e40-2a4457f09bf0,NT AUTHORITY\SYSTEM,4624,2019-02-12 21:53:53.453,263a788b-6526-4cdc-8ed9-d79402fe4aa0,MSTICAlertsWin1,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7,Advapi,5,Negotiate,,-,-,2019-02-12 21:53:53.453

## Joining columns (horizontal)

In [155]:
df_col_1 = logons_full_df[0:10].filter(regex="Subject.*")
df_col_2 = logons_full_df[0:10].filter(regex="Target.*")
print(df_col_1.shape, df_col_2.shape)
df_col_1.head()

(10, 3) (10, 4)

    SubjectUserName SubjectDomainName SubjectUserSid
0  MSTICAlertsWin1$         WORKGROUP       S-1-5-18
1                 -                 -        S-1-0-0
2                 -                 -        S-1-0-0
3                 -                 -        S-1-0-0
4                 -                 -        S-1-0-0

In [160]:
pd.concat([df_col_1, df_col_2], axis="columns")

,SubjectUserName,SubjectDomainName,SubjectUserSid,TargetUserName,TargetDomainName,TargetUserSid,TargetLogonId
0,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7
1,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90e957
2,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc90ea44
3,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc912d62
4,-,-,S-1-0-0,MSTICAdmin,MSTICAlertsWin1,S-1-5-21-996632719-2361334927-4038480536-500,0xc913737
5,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7
6,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7
7,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7
8,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7
9,MSTICAlertsWin1$,WORKGROUP,S-1-5-18,SYSTEM,NT AUTHORITY,S-1-5-18,0x3e7